---
name: "Sprint board maintenance"
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  label_open_boards:
    name: "Sprint board maintenance"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Set up python"
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install -e .

      - name: "Manage accepted label"
        run: |
          pipenv run moc-sprint-tools -v label-cards-in-sprint
        env:
          GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}

      - name: "Sort priority tagged cards"
        run: |
          pipenv run moc-sprint-tools -v sort-cards-by-priority
        env:
          GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}

      - name: "Add needs_description label"
        run: |
          pipenv run moc-sprint-tools -v label-needs-description
        env:
          GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}

      - name: "Add missing cards to backlog"
        run: |
          pipenv run moc-sprint-tools -v cards-missing-from-backlog
        env:
          GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}

      - name: "Close out old sprints"
        run: |
          pipenv run moc-sprint-tools -v close-sprint-boards
        env:
          GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}

      - name: "Create new sprints"
        run: |
          pipenv run moc-sprint-tools -v create-sprint-boards
        env:
          GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
